version: 0.2

phases:
  install:
    commands:
      - curl -sL https://rpm.nodesource.com/setup_18.x | bash -
      - yum install -y nodejs
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - echo Deploying to S3...
      - aws s3 sync frontend/build/ s3://carsales-frontend-prod --delete
      - aws cloudfront create-invalidation --distribution-id E19VEVVFP1O8WS --paths "/*"

artifacts:
  files:
    - '**/*'
  base-directory: frontend/build
