version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm ci

  build:
    commands:
      - echo Building frontend...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
